/**
 * UNDERCOVER PARTY GAME — WORD BANK
 * Single flat pool of word pairs. Randomly picked each game.
 * Format: { civ: "Word A", under: "Word B" }
 */

const WORD_BANK = [

  // ── LANDMARKS & MONUMENTS ──
  { civ: "Taj Mahal",           under: "Qutub Minar"        },
  { civ: "Eiffel Tower",        under: "Burj Khalifa"        },
  { civ: "Red Fort",            under: "India Gate"          },
  { civ: "Statue of Liberty",   under: "Christ the Redeemer" },
  { civ: "Colosseum",           under: "Pantheon"            },
  { civ: "Great Wall",          under: "Berlin Wall"         },
  { civ: "Pyramid",             under: "Temple"              },
  { civ: "Palace",              under: "Fort"                },
  { civ: "Museum",              under: "Gallery"             },
  { civ: "Park",                under: "Garden"              },

  // ── TRANSPORT ──
  { civ: "Car",                 under: "Taxi"                },
  { civ: "Bike",                under: "Scooter"             },
  { civ: "Bus",                 under: "Metro"               },
  { civ: "Train",               under: "Tram"                },
  { civ: "Airplane",            under: "Helicopter"          },
  { civ: "Ship",                under: "Boat"                },
  { civ: "Truck",               under: "Pickup"              },
  { civ: "Bicycle",             under: "Rickshaw"            },
  { civ: "Jet",                 under: "Rocket"              },
  { civ: "Submarine",           under: "Ship"                },

  // ── FOOD & DRINKS ──
  { civ: "Burger",              under: "Sandwich"            },
  { civ: "Pizza",               under: "Pasta"               },
  { civ: "Tea",                 under: "Coffee"              },
  { civ: "Coke",                under: "Pepsi"               },
  { civ: "Rice",                under: "Biryani"             },
  { civ: "Noodles",             under: "Spaghetti"           },
  { civ: "Chocolate",           under: "Candy"               },
  { civ: "Ice Cream",           under: "Kulfi"               },
  { civ: "Bread",               under: "Roti"                },
  { civ: "Butter",              under: "Cheese"              },

  // ── TECH & GADGETS ──
  { civ: "Phone",               under: "Tablet"              },
  { civ: "Laptop",              under: "Computer"            },
  { civ: "Android",             under: "iPhone"              },
  { civ: "Instagram",           under: "Snapchat"            },
  { civ: "YouTube",             under: "Netflix"             },
  { civ: "Google",              under: "Bing"                },
  { civ: "Keyboard",            under: "Mouse"               },
  { civ: "WiFi",                under: "Bluetooth"           },
  { civ: "Charger",             under: "Powerbank"           },
  { civ: "Camera",              under: "CCTV"                },

  // ── ENTERTAINMENT & POP CULTURE ──
  { civ: "Movie",               under: "Web Series"          },
  { civ: "Actor",               under: "Influencer"          },
  { civ: "Cinema",              under: "Theatre"             },
  { civ: "Song",                under: "Music"               },
  { civ: "Rap",                 under: "Pop"                 },
  { civ: "Comedy",              under: "Meme"                },
  { civ: "Netflix",             under: "Amazon Prime"        },
  { civ: "PUBG",                under: "Free Fire"           },
  { civ: "GTA",                 under: "Need for Speed"      },
  { civ: "Cricket",             under: "Football"            },

  // ── SCHOOL & HOME ──
  { civ: "School",              under: "College"             },
  { civ: "Teacher",             under: "Professor"           },
  { civ: "Book",                under: "Notebook"            },
  { civ: "Pen",                 under: "Pencil"              },
  { civ: "Bag",                 under: "Backpack"            },
  { civ: "Chair",               under: "Sofa"                },
  { civ: "Bed",                 under: "Mattress"            },
  { civ: "Room",                under: "Hall"                },
  { civ: "Window",              under: "Door"                },
  { civ: "Fan",                 under: "AC"                  },

  // ── NATURE ──
  { civ: "River",               under: "Lake"                },
  { civ: "Ocean",               under: "Sea"                 },
  { civ: "Mountain",            under: "Hill"                },
  { civ: "Sun",                 under: "Moon"                },
  { civ: "Rain",                under: "Snow"                },
  { civ: "Desert",              under: "Forest"              },
  { civ: "Sky",                 under: "Space"               },
  { civ: "Fire",                under: "Lava"                },
  { civ: "Wind",                under: "Storm"               },
  { civ: "Tree",                under: "Plant"               },

  // ── FASHION & CLOTHING ──
  { civ: "Shirt",               under: "T-Shirt"             },
  { civ: "Jeans",               under: "Pants"               },
  { civ: "Shoes",               under: "Sneakers"            },
  { civ: "Jacket",              under: "Hoodie"              },
  { civ: "Cap",                 under: "Helmet"              },
  { civ: "Watch",               under: "Bracelet"            },
  { civ: "Glasses",             under: "Goggles"             },
  { civ: "Suit",                under: "Blazer"              },
  { civ: "Kurta",               under: "Sherwani"            },
  { civ: "Saree",               under: "Lehenga"             },

  // ── PROFESSIONS ──
  { civ: "Doctor",              under: "Nurse"               },
  { civ: "Police",              under: "Army"                },
  { civ: "Judge",               under: "Lawyer"              },
  { civ: "Boss",                under: "Manager"             },
  { civ: "Owner",               under: "Employee"            },
  { civ: "Hero",                under: "Actor"               },
  { civ: "Singer",              under: "Rapper"              },
  { civ: "Chef",                under: "Cook"                },
  { civ: "Pilot",               under: "Driver"              },
  { civ: "Artist",              under: "Designer"            },

  // ── PSYCHOLOGICAL & ABSTRACT ──
  { civ: "Confidence",          under: "Arrogance"           },
  { civ: "Smart",               under: "Intelligent"         },
  { civ: "Love",                under: "Attraction"          },
  { civ: "Fame",                under: "Respect"             },
  { civ: "Jealous",             under: "Insecure"            },
  { civ: "Hardwork",            under: "Talent"              },
  { civ: "Luck",                under: "Destiny"             },
  { civ: "Truth",               under: "Fact"                },
  { civ: "Knowledge",           under: "Wisdom"              },
  { civ: "Fear",                under: "Anxiety"             },
  { civ: "Leader",              under: "Boss"                },
  { civ: "Friend",              under: "Best Friend"         },
  { civ: "Job",                 under: "Career"              },
  { civ: "Win",                 under: "Success"             },
  { civ: "Power",               under: "Authority"           },
  { civ: "Influence",           under: "Control"             },
  { civ: "Luxury",              under: "Comfort"             },
  { civ: "Calm",                under: "Quiet"               },
  { civ: "Risk",                under: "Danger"              },
  { civ: "Funny",               under: "Sarcastic"           },
  { civ: "Hero",                under: "Villain"             },
  { civ: "Normal",              under: "Weird"               },
  { civ: "Private",             under: "Secret"              },
  { civ: "Game",                under: "Sport"               },
  { civ: "Angry",               under: "Annoyed"             },
  { civ: "Respect",             under: "Fear"                },
  { civ: "Cheap",               under: "Affordable"          },
  { civ: "Team",                under: "Group"               },
  { civ: "Alone",               under: "Lonely"              },
  { civ: "Fast",                under: "Quick"               },
  { civ: "Strong",              under: "Tough"               },
  { civ: "Brave",               under: "Fearless"            },
  { civ: "Introvert",           under: "Antisocial"          },
  { civ: "Rich",                under: "Wealthy"             },
  { civ: "Freedom",             under: "Independence"        },
  { civ: "Dream",               under: "Goal"                },
  { civ: "City",                under: "Society"             },
  { civ: "School",              under: "Education"           },
  { civ: "Sleep",               under: "Rest"                },
  { civ: "Work",                under: "Job"                 },

  // ── RELATABLE / GEN-Z ──
  { civ: "Girlfriend",          under: "Crush"               },
  { civ: "Wife",                under: "Mom"                 },
  { civ: "Teacher",             under: "Principal"           },
  { civ: "Homework",            under: "Exam"                },
  { civ: "Party",               under: "Wedding"             },
  { civ: "Rich",                under: "Broke"               },
  { civ: "Gym",                 under: "Diet"                },
  { civ: "Sleep",               under: "Netflix"             },
  { civ: "Study",               under: "Cheating"            },
  { civ: "Friend",              under: "Enemy"               },
  { civ: "Money",               under: "Happiness"           },
  { civ: "Time",                under: "Money"               },
  { civ: "Phone",               under: "Addiction"           },
  { civ: "Love",                under: "Drama"               },
  { civ: "Truth",               under: "Lie"                 },
  { civ: "Online",              under: "Offline"             },
  { civ: "Public",              under: "Private"             },
  { civ: "Famous",              under: "Viral"               },
  { civ: "Game",                under: "Gamble"              },
  { civ: "Win",                 under: "Lose"                },

  // ── EXTRA PSYCHOLOGICAL & SOCIAL ──
  { civ: "Love",                under: "Obsession"           },
  { civ: "Empathy",             under: "Sympathy"            },
  { civ: "Habit",               under: "Addiction"           },
  { civ: "Grief",               under: "Depression"          },
  { civ: "Courage",             under: "Recklessness"        },
  { civ: "Honest",              under: "Blunt"               },
  { civ: "Apology",             under: "Excuse"              },
  { civ: "Criticism",           under: "Feedback"            },
  { civ: "Reputation",          under: "Image"               },
  { civ: "Argument",            under: "Discussion"          },
  { civ: "Memory",              under: "Nostalgia"           },
  { civ: "Justice",             under: "Revenge"             },
  { civ: "Selfish",             under: "Self-Care"           },
  { civ: "Sacrifice",           under: "Loss"                },
  { civ: "Corruption",          under: "Dishonesty"          },
  { civ: "Woke",                under: "Aware"               },
  { civ: "Cancelled",           under: "Banned"              },
  { civ: "Vibe",                under: "Mood"                },
  { civ: "Red Flag",            under: "Warning Sign"        },
  { civ: "Rizz",                under: "Charm"               },
  { civ: "Lowkey",              under: "Secretly"            },
  { civ: "Clout",               under: "Fame"                },
  { civ: "Toxic",               under: "Negative"            },
  { civ: "FOMO",                under: "Jealousy"            },
  { civ: "Cringe",              under: "Embarrassing"        },
  { civ: "Delulu",              under: "Delusional"          },
  { civ: "NPC",                 under: "Robot"               },
  { civ: "Gossip",              under: "Tea"                 },
  { civ: "Nerd",                under: "Geek"                },
  { civ: "Side Hustle",         under: "Freelancing"         },
  { civ: "Overthinking",        under: "Worrying"            },
  { civ: "Stubborn",            under: "Determined"          },
  { civ: "Procrastinate",       under: "Lazy"                },
  { civ: "Awkward",             under: "Weird"               },

];

/**
 * Get a random word pair from the flat pool.
 * @returns {{ civ: string, under: string }}
 */
function getRandomPair() {
  return WORD_BANK[Math.floor(Math.random() * WORD_BANK.length)];
}
